### ISSUE TITLE
STARTER TASK - Add all VLANs allowed on a Cisco trunk interface

### ISSUE THREAD

**Issue by palisadoes** [UWICompSociety/infoset#25]
You can use the the following Cisco MIB values to determine VLANs on a port. They are keyed on ifIndex values.

1. CISCO-VTP-MIB::vlanTrunkPortVlansEnabled 
2. CISCO-VTP-MIB::vlanTrunkPortVlansEnabled2k
3. CISCO-VTP-MIB::vlanTrunkPortVlansEnabled2k
4. CISCO-VTP-MIB::vlanTrunkPortVlansEnabled2k

In the device's YAML files, make the VLANs a list under the following stucture
```
Layer 1:
 ifindex_value:
  vlanTrunkPortVlansEnabled
   - 1
   - 2
   - 3
  vlanTrunkPortVlansEnabled2k:
   - 1
   - 2
   - 3
   - vlan z
  vlanTrunkPortVlansEnabled3k:
   - 1
   - 2
   - 3
   - vlan x
  vlanTrunkPortVlansEnabled4k:
   - 1
   - 2
   - 3
   - vlan y
```
The `_vlan` function in `xlate_snmp.py` will need to be modified to accommodate this feature by updating the VLAN list presented.

The existing jnxExVlanTag functionality works for Juniper.

Must support Cisco and Juniper gear.

Unittests required.

===============

HTMLTable class ethernet method in the lib/web/snmp/ws_device.py file will need to list all the allowed VLANs on the port if it is a trunk. If specific ones are defined. If not just say “Trunk port”.

Sample output can be found here where 192.168.1.1 is detected: http://calico.palisadoes.org/switchmap/www/switches/192.168.1.3.html

Must support Cisco and Juniper gear.

There is no need to create CSS for this. Focus on basic functionality.

Must include unittests.

You can use the jm_trunk key from the Translator class to determine whether a port is a trunk or not.
